openapi: '3.0.0'
info:
  version: 0.0.1
  title: mfacilitate-spec

paths:
  /meetings:
    get:
      summary: List all meetings
      operationId: listMeetings
      tags:
        - meetings
      responses:
        '200':
          description: A paged array of meetings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetings'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a meetings
      operationId: createMeetings
      tags:
        - meetings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeetingPostRequestBody'
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /themes:
    get:
      summary: List all themes
      operationId: listThemes
      tags:
        - themes
      responses:
        '200':
          description: A paged array of themes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Themes'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a themes
      operationId: createThemes
      tags:
        - themes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThemesPostRequestBody'
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Meetings:
      type: 'object'
      required:
        - meeting_id
        - title
        - start_at
        - created_at
        - updated_at
      properties:
        meeting_id:
          type: string
          format: uuid
        start_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Themes:
      type: 'object'
      required:
        - theme_id
        - title
        - description
        - url
        - time
        - created_at
        - updated_at
      properties:
        theme_id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        url:
          type: string
        time:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    MeetingPostRequestBody:
      type: 'object'
      required:
        - meeting_id
      properties:
        meeting_id:
          type: string
          format: uuid
        start_at:
          type: string
          format: date-time
    ThemesPostRequestBody:
      type: 'object'
      required:
        - theme_id
        - title
        - url
        - time
      properties:
        theme_id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        url:
          type: string
        time:
          type: integer
    PostResponse:
      type: 'object'
      required:
        - statusText
      properties:
        statusText:
          type: string
    Error:
      type: 'object'
      required:
        - error
        - status
        - statusText
      properties:
        error:
          type: string
        status:
          type: integer
        statusText:
          type: string
